
CREATE OR REPLACE 
PACKAGE pldoc_bug.test_case_3048528 
AS

FUNCTION getCachedValue(KEY IN T_SETTINGS.SET_KEY%TYPE) 
RETURN T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE ;


FUNCTION getReliesCachedValue(KEY IN T_SETTINGS.SET_KEY%TYPE) 
RETURN T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(T_SETTINGS) ;


FUNCTION getMultiReliesCachedValue(KEY IN T_SETTINGS.SET_KEY%TYPE) 
RETURN T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(T_SETTINGS,T_GETTINGS) ;

FUNCTION getOtherCachedValue(KEY IN OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE) 
RETURN OTHER_SCHEMA.T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE ;

FUNCTION getOtherReliesCachedValue(KEY IN OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE) 
RETURN OTHER_SCHEMA.T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(OTHER_SCHEMA.T_SETTINGS) ;

FUNCTION getOtherMultiReliesCachedValue(KEY IN OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE) 
RETURN OTHER_SCHEMA.T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(OTHER_SCHEMA.T_SETTINGS,OTHER_SCHEMA.T_GETTINGS) ;

END;
/


CREATE OR REPLACE 
PACKAGE BODY pldoc_bug.test_case_3048528 
AS

FUNCTION getCachedValue(KEY IN T_SETTINGS.SET_KEY%TYPE) 
RETURN T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE IS

result T_SETTINGS.SET_KEY%TYPE;
BEGIN
SELECT SET_VALUE INTO result FROM T_SETTINGS WHERE SET_KEY = KEY;
RETURN result;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END ;

FUNCTION getReliesCachedValue(KEY IN T_SETTINGS.SET_KEY%TYPE) 
RETURN T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(T_SETTINGS) IS

result T_SETTINGS.SET_KEY%TYPE;
BEGIN
SELECT SET_VALUE INTO result FROM T_SETTINGS WHERE SET_KEY = KEY;
RETURN result;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END ;

FUNCTION getMultiReliesCachedValue(KEY IN T_SETTINGS.SET_KEY%TYPE) 
RETURN T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(T_SETTINGS,T_GETTINGS) IS

result T_SETTINGS.SET_KEY%TYPE;
BEGIN
SELECT SET_VALUE 
INTO result 
FROM T_SETTINGS 
NATURAL JOIN T_GETTINGS 
WHERE SET_KEY = KEY;
RETURN result;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END ;

FUNCTION getOtherCachedValue(KEY IN OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE) 
RETURN OTHER_SCHEMA.T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE IS

result OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE;
BEGIN
SELECT SET_VALUE INTO result FROM OTHER_SCHEMA.T_SETTINGS WHERE SET_KEY = KEY;
RETURN result;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END ;

FUNCTION getOtherReliesCachedValue(KEY IN OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE) 
RETURN OTHER_SCHEMA.T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(OTHER_SCHEMA.T_SETTINGS) IS

result OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE;
BEGIN
SELECT SET_VALUE INTO result FROM OTHER_SCHEMA.T_SETTINGS WHERE SET_KEY = KEY;
RETURN result;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END ;

FUNCTION getOtherMultiReliesCachedValue(KEY IN OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE) 
RETURN OTHER_SCHEMA.T_SETTINGS.SET_VALUE%TYPE 
RESULT_CACHE RELIES_ON(OTHER_SCHEMA.T_SETTINGS,OTHER_SCHEMA.T_GETTINGS) IS

result OTHER_SCHEMA.T_SETTINGS.SET_KEY%TYPE;
BEGIN
SELECT SET_VALUE 
INTO result 
FROM OTHER_SCHEMA.T_SETTINGS 
NATURAL JOIN OTHER_SCHEMA.T_GETTINGS 
WHERE SET_KEY = KEY;
RETURN result;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END ;

END;
/

