CREATE USER pldoc IDENTIFIED BY pldoc ;

ALTER USER pldoc ACCOUNT UNLOCK;

GRANT CONNECT TO pldoc;

GRANT SELECT ANY DICTIONARY TO pldoc;

GRANT SELECT_CATALOG_ROLE TO pldoc;


ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME unlimited;

ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME  unlimited;
