CREATE OR REPLACE
TYPE         TY_LOCATION AS OBJECT
(
  NAME     VARCHAR2(500),
  LATITUDE NUMBER,
  LONGITUDE NUMBER,
  DATUM VARCHAR2(10),
  MEMBER FUNCTION GET_NAME RETURN VARCHAR2,
  MEMBER FUNCTION GET_DATUM RETURN VARCHAR2,
  MEMBER FUNCTION GET_LATITUDE RETURN NUMBER,
  MEMBER FUNCTION GET_LONGITUDE RETURN NUMBER
)
/

SHOW ERRORS 
