
  CREATE OR REPLACE FUNCTION "MDSYS"."OGC_AREA" (
  s ST_Geometry)
    RETURN NUMBER DETERMINISTIC IS
BEGIN
  IF(UPPER(OGC_GeometryType(s)) IN ('POLYGON', 'ST_POLYGON')) THEN
    RETURN TREAT(s AS ST_Surface).ST_Area();
  END IF;
  IF(UPPER(OGC_GeometryType(s)) IN ('MULTIPOLYGON', 'ST_MULTIPOLYGON')) THEN
    RETURN TREAT(s AS ST_MultiSurface).ST_Area();
  END IF;
  RETURN NULL;
END OGC_Area;

